---
homebrew_cask_apps:
  - adobe-acrobat-reader
  - db-browser-for-sqlite
  - deepl
  - disk-inventory-x
  - drawio
  - google-drive
  - imageoptim
  - iterm2
  - keepassxc
  - licecap
  - logseq
  - michaelvillar-timer
  - musicbrainz-picard
  - openemu
  - postman
  - qlcolorcode
  - quicklook-json
  - qlprettypatch
  - quicklook-csv
  - qlimagesize
  - sequel-pro
  - sourcetree
  - spectacle
  - spotify
  - suspicious-package
  - table-tool
  - the-unarchiver
  - timelapze
  - tomighty
  - visual-studio-code
  - vlc
  - vox
  - vox-preferences-pane
  - webpquicklook
  - youtube-to-mp3

homebrew_installed_packages:
  - coreutils
  #- ddev
  - derailed/k9s/k9s
  - dive
  # Fix the iterm error caused by viasite-ansible.zsh
  # Error message: (anon):7: command not found: fd
  # Cause by a requirement of fzf_widgets: sorenson-axial/fzf-widgets
  - fd
  - findutils
  - fzf
  - git
  - git-extras
  - gnu-tar
  - htop
  - lzop
  - moreutils
  - mysql
  - nvm
  - rsync
  - sqlmap
  - tree
  - wget
  - zsh
  - zsh-completions

mas_installed_apps:
  - { id: 6463294724, name: "Muteem" }
  - { id: 984929789, name: "Duplicate Photos Finder" }
  - { id: 1450640351, name: "Lightweight PDF" }

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
dockitems_persist:
  - name: "Logseq"
    path: "/Applications/Logseq.app"
    pos: 1

  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 2

  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app"
    pos: 3

  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app"
    pos: 4

  - name: "Sourcetree"
    path: "/Applications/Sourcetree.app"
    pos: 5

  - name: "iTerm"
    path: "/Applications/iTerm.app"
    pos: 6

zsh_autosuggestions_bind_key: "^U"
zsh_hotkeys_extras:
  - { hotkey: "^[^[[D", action: backward-word } # alt+left
  - { hotkey: "^[^[[C", action: forward-word } # alt+right
zsh_antigen_bundles_extras:
  - nvm
  - joel-porquet/zsh-dircolors-solarized
  - { name: macos, when: "{{ ansible_os_family == 'Darwin' }}" }

osx_defaults:
  - domain: "com.apple.menuextra.clock"
    key: "DateFormat"
    type: string
    value: "EEE MMM d  h:mm a"
  - domain: "com.googlecode.iterm2"
    key: "PromptOnQuit"
    type: bool
    value: false
  # Set Desktop as the default location for new Finder windows use `PfHm`
  # For other paths, use `PfLo`
  - domain: "com.apple.finder"
    key: "NewWindowTarget"
    type: string
    value: "PfLo"
  - domain: "com.apple.finder"
    key: "NewWindowTargetPath"
    type: string
    value: "file://${HOME}/"

composer_packages: []
npm_packages: []
pip_packages: []
