---
- name: Configure host
  hosts: all

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: bussmeyer.dotfiles
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: viasite-ansible.zsh
      tags: ['zsh']

  vars_files:
    - default.config.yml

  tasks:
    - name: set mac defaults
      osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
      with_items: "{{ osx_defaults }}"
      tags: ['osx']
    - import_tasks: tasks/terminal.yml
      tags: ['zsh']
    - import_tasks: tasks/packages.yml
      tags: ['packages']
    - name: create ~/Projects directory
      file: path=~/Projects state=directory
      tags: ['projects']
    # - name: Restart SystemUIServer e.g. show date in menu
    #   command: killall SystemUIServer
    #   tags: ['osx']

