---
- hosts: all
  connection: local

  roles:
    - bussmeyer.dotfiles
    - geerlingguy.homebrew
    - viasite-ansible.zsh

  vars:
    composer_packages:
      - name: hirak/prestissimo
      - name: drush/drush
        version: '^8.1'
      - name: squizlabs/php_codesniffer
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - caskroom/versions
      - codekitchen/dinghy
    homebrew_cask_apps:
      # install applications for all users
      - box-sync
      - drawio
      - firefox
      - licecap
      - microsoft-teams
      - the-unarchiver
      - vlc
      - yed
      # developer apps
      - atom
      - charles
      - cyberduck
      - db-browser-for-sqlite
      - docker
      - filezilla
      - forticlient
      - keepassx
      - kitematic
      - imagealpha
      - imageoptim
      - istat-menus
      - iterm2
      - macdown
      - mamp
      - pgadmin4
      - phpstorm
      - postman
      - sequel-pro
      - sketch
      - sourcetree
      - sublime-text
      - vagrant
      - vmware-fusion
      - virtualbox
      - webstorm
      - wireshark
      # install quick look plugins for all users
      - qlcolorcode
      - qlstephen
      - qlmarkdown
      - quicklook-json
      - qlprettypatch
      - quicklook-csv
      - betterzipql
      - qlimagesize
      - webpquicklook
      - suspicious-package
    homebrew_installed_packages:
      - composer
      - coreutils
      - docker
      - docker-compose
      - docker-machine
      - docker-machine-driver-xhyve
      - dinghy
      - findutils
      - fzf
      - git
      - git-extras
      - gnu-tar
      - htop
      - moreutils
      - mysql
      - nvm
      - python
      - rbenv
      - rsync
      - sqlmap
      - tree
      - wget
      - yarn
      - zsh
      - zsh-completions
    gem_packages:
      - name: docker-sync
        state: latest
    npm_packages:
      - name: grunt
    osx_defaults:
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      - domain: 'com.apple.desktopservices' # http://www.defaults-write.com/disable-the-creation-of-ds_store-files/
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: true
      - domain: 'com.apple.print.PrintingPrefs' # Automatically quit printer app once the print jobs complete
        key: 'Quit When Finished'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeInternalDebugMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeDevelopMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'WebKitDeveloperExtras'
        type: boolean
        value: true
    zsh_autosuggestions_bind_key: "^U"
    zsh_antigen_bundles_extras:
      - composer
      - git-flow
      - nvm
      - { name: osx, when: "{{ ansible_os_family == 'Darwin' }}" }

  tasks:
    - name: set mac defaults
      osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
      with_items: "{{ osx_defaults }}"
      tags:
        - osx
    - name: create /tmp/powerline directory
      file: path=/tmp/powerline state=directory
      tags:
        - shell
    - name: git clone Powerline fonts repository
      git: repo='https://github.com/powerline/fonts.git' dest=/tmp/powerline
      tags:
        - shell
    - name: install Powerline fonts
      command: ./install.sh
      args:
        chdir: /tmp/powerline
      tags:
        - shell
    - name: cleanup Powerline fonts installation
      file: path=/tmp/powerline state=absent
      tags:
        - shell
    - name: ".zshrc.local"
      template:
        src: templates/zshrc.local
        dest: ~/.zshrc.local
      tags:
        - dotfiles
    - name: Install global Composer packages.
      composer:
        command: "{{ (item.state | default('present') == 'absent') | ternary('remove', 'require') }}"
        arguments: "{{ item.name | default(item) }} {{ item.version | default('@stable') }}"
        # Ansible 2.4 supports `global_command` making `working_dir` optional.
        working_dir: "{{ lookup('env', 'COMPOSER_HOME') | default('~/.composer', true) }}"
      with_items: "{{ composer_packages }}"
      tags:
        - composer
    - name: Install global Ruby gems.
      gem:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        user_install: no
        executable: "{{ item.executable | default(omit) }}"
      with_items: "{{ gem_packages }}"
      tags:
        - gems
    - name: Install global NPM packages.
      npm:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        global: yes
        executable: "{{ item.executable | default(omit) }}"
      with_items: "{{ npm_packages }}"
      tags:
        - npm
    - name: create ~/Projects directory
      file: path=~/Projects state=directory
      tags:
        - projects
