---
- name: Configure host
  hosts: all

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: bussmeyer.dotfiles
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: viasite-ansible.zsh
      tags: ['zsh']

  vars_files:
    - default.config.yml

  tasks:
    - name: set mac defaults
      osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
      with_items: "{{ osx_defaults }}"
      tags: ['osx']
#     - name: create /tmp/powerline directory
#       file: path=/tmp/powerline state=directory
#       tags:
#         - shell
#     - name: git clone Powerline fonts repository
#       git: repo='https://github.com/powerline/fonts.git' dest=/tmp/powerline
#       tags:
#         - shell
#     - name: install script of Powerline fonts
#       command: /tmp/powerline/install.sh
#       tags:
#         - shell
#     - name: cleanup Powerline fonts installation
#       file: path=/tmp/powerline state=absent
#       tags:
#         - shell
#     - name: Import iTerm2 settings, incl. fonts
#       copy:
#         src: templates/com.googlecode.iterm2.plist
#         dest: ~/Library/Preferences/com.googlecode.iterm2.plist
#       tags:
#         - shell
#     - name: ".zshrc.local"
#       template:
#         src: templates/zshrc.local
#         dest: ~/.zshrc.local
#       tags:
#         - dotfiles
#     - name: Install global Composer packages.
#       composer:
#         command: "{{ (item.state | default('present') == 'absent') | ternary('remove', 'require') }}"
#         arguments: "{{ item.name | default(item) }} {{ item.version | default('@stable') }}"
#         # Ansible 2.4 supports `global_command` making `working_dir` optional.
#         working_dir: "{{ lookup('env', 'COMPOSER_HOME') | default('~/.composer', true) }}"
#       with_items: "{{ composer_packages }}"
#       tags:
#         - composer
#     - name: Install global NPM packages.
#       npm:
#         name: "{{ item.name | default(item) }}"
#         state: "{{ item.state | default('present') }}"
#         version: "{{ item.version | default(omit) }}"
#         global: yes
#         executable: "{{ item.executable | default(omit) }}"
#       with_items: "{{ npm_packages }}"
#       tags:
#         - npm
#     - name: Install python packages.
#       pip:
#         name: "{{ item.name | default(item) }}"
#       with_items: "{{ pip_packages }}"
#       tags:
#         - pip
#     - name: create ~/Projects directory
#       file: path=~/Projects state=directory
#       tags:
#         - projects
    - name: Restart SystemUIServer e.g. show date in menu
      command: killall SystemUIServer
      tags: ['osx']
