---
- hosts: all
  connection: local

  roles:
    - bussmeyer.dotfiles
    - geerlingguy.homebrew
    - viasite-ansible.zsh

  vars:
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - caskroom/versions
      - codekitchen/dinghy
    homebrew_cask_apps:
      # install applications for all users
      - box-sync
      - drawio
      - firefox
      - microsoft-lync
      - microsoft-teams
      - vlc
      - yed
      # developer apps
      - docker
      - kitematic
      - imagealpha
      - imageoptim
      - istat-menus
      - macdown
      - mamp
      - phpstorm
      - postman
      - sequel-pro
      - sourcetree
      - vagrant
      - virtualbox
      - wireshark
      # install quick look plugins for all users
      - qlcolorcode
      - qlstephen
      - qlmarkdown
      - quicklook-json
      - qlprettypatch
      - quicklook-csv
      - betterzipql
      - qlimagesize
      - webpquicklook
      - suspicious-package
    homebrew_installed_packages:
      - composer
      - coreutils
      - docker
      - docker-compose
      - docker-machine
      - docker-machine-driver-xhyve
      - dinghy
      - findutils
      - fzf
      - git
      - git-extras
      - htop
      - moreutils
      - nvm
      - phpmd
      - php-code-sniffer
      - php-cs-fixer
      - phpunit
      - php70
      - php70-intl
      - php70-imagick
      - php70-mcrypt
      - python
      - rbenv
      - rsync
      - sqlmap
      - tree
      - wget
      - yarn
      - zsh
      - zsh-completions
    osx_defaults:
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      - domain: 'com.apple.desktopservices' # http://www.defaults-write.com/disable-the-creation-of-ds_store-files/
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: true
      - domain: 'com.apple.print.PrintingPrefs' # Automatically quit printer app once the print jobs complete
        key: 'Quit When Finished'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeInternalDebugMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeDevelopMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'WebKitDeveloperExtras'
        type: boolean
        value: true
    zsh_autosuggestions_bind_key: "^U"
    zsh_antigen_bundles_extras:
      - composer
      - git-flow
      - nvm
      - { name: osx, when: "{{ ansible_os_family == 'Darwin' }}" }

  tasks:
    - name: create ~/Projects directory
      file: path=~/Projects state=directory
    - name: set mac defaults
      osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
      with_items: "{{ osx_defaults }}"
    - name: create /usr/local/powerline directory
      file: path=/usr/local/powerline state=directory
      tags:
        - powerline
    - name: git clone Powerline fonts repository
      git: repo='https://github.com/powerline/fonts.git' dest=/usr/local/powerline/fonts
      tags:
        - powerline
    - name: install Powerline fonts
      command: ./install.sh
      args:
        chdir: /usr/local/powerline/fonts/
      tags:
        - powerline
    - name: cleanup Powerline fonts installation
      file: path=/usr/local/powerline/fonts state=absent
      tags:
        - powerline
    - name: .zshrc.local
      template:
        src: templates/zshrc.local
        dest: ~/.zshrc.local
      tags:
        - dotfiles
