---
- hosts: all
  connection: local

  roles:
    - bussmeyer.dotfiles
    - geerlingguy.homebrew
    - viasite-ansible.zsh

  vars:
    composer_packages:
      - name: hirak/prestissimo
      - name: drush/drush
        version: '^8.1'
      - name: squizlabs/php_codesniffer
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - caskroom/versions
      - codekitchen/dinghy
    homebrew_cask_apps:
      # install applications for all users
      - box-sync
      - drawio
      - firefox
      - licecap
      - microsoft-lync
      - microsoft-teams
      - vlc
      - yed
      # developer apps
      - docker
      - kitematic
      - imagealpha
      - imageoptim
      - istat-menus
      - macdown
      - mamp
      - phpstorm
      - postman
      - sequel-pro
      - sourcetree
      - sublime-text
      - vagrant
      - virtualbox
      - wireshark
      # install quick look plugins for all users
      - qlcolorcode
      - qlstephen
      - qlmarkdown
      - quicklook-json
      - qlprettypatch
      - quicklook-csv
      - betterzipql
      - qlimagesize
      - webpquicklook
      - suspicious-package
    homebrew_installed_packages:
      - composer
      - coreutils
      - docker
      - docker-compose
      - docker-machine
      - docker-machine-driver-xhyve
      - dinghy
      - findutils
      - fzf
      - git
      - git-extras
      - htop
      - moreutils
      - nvm
      - python
      - rbenv
      - rsync
      - sqlmap
      - tree
      - wget
      - yarn
      - zsh
      - zsh-completions
    osx_defaults:
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      - domain: 'com.apple.desktopservices' # http://www.defaults-write.com/disable-the-creation-of-ds_store-files/
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: true
      - domain: 'com.apple.print.PrintingPrefs' # Automatically quit printer app once the print jobs complete
        key: 'Quit When Finished'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeInternalDebugMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeDevelopMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'WebKitDeveloperExtras'
        type: boolean
        value: true
    zsh_autosuggestions_bind_key: "^U"
    zsh_antigen_bundles_extras:
      - composer
      - git-flow
      - nvm
      - { name: osx, when: "{{ ansible_os_family == 'Darwin' }}" }
    projects:
      - group: mwide-nrw
        name: mwide-nrw-startercenter
        repo: git@git.pixelpark.com:MWIDE-NRW/mwide-nrw-startercenter.git
      - group: dummy
        name: horst
        repo: git@git.pixelpark.com:MWIDE-NRW/mwide-nrw-startercenter.git

  tasks:
    - name: set mac defaults
      osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
      with_items: "{{ osx_defaults }}"
      tags:
        - osx
    - name: create /usr/local/powerline directory
      file: path=/usr/local/powerline state=directory
      tags:
        - shell
    - name: git clone Powerline fonts repository
      git: repo='https://github.com/powerline/fonts.git' dest=/usr/local/powerline/fonts
      tags:
        - shell
    - name: install Powerline fonts
      command: ./install.sh
      args:
        chdir: /usr/local/powerline/fonts/
      tags:
        - shell
    - name: cleanup Powerline fonts installation
      file: path=/usr/local/powerline/fonts state=absent
      tags:
        - shell
    - name: ".zshrc.local"
      template:
        src: templates/zshrc.local
        dest: ~/.zshrc.local
      tags:
        - dotfiles
    - name: Install global Composer packages.
      composer:
        command: "{{ (item.state | default('present') == 'absent') | ternary('remove', 'require') }}"
        arguments: "{{ item.name | default(item) }} {{ item.version | default('@stable') }}"
        # Ansible 2.4 supports `global_command` making `working_dir` optional.
        working_dir: "{{ lookup('env', 'COMPOSER_HOME') | default('~/.composer', true) }}"
      with_items: "{{ composer_packages }}"
      tags:
        - composer
    - name: create ~/Projects directory
      file: path=~/Projects state=directory
      tags:
        - projects
    - name: create a directory for each client
      file: path=~/Projects/{{ item.group }} state=directory
      with_items: "{{ projects }}"
      tags:
        - projects
    - name: clone client projects
      git:
        repo: "{{ item.repo }}"
        dest: ~/Projects/{{ item.group }}/{{ item.name}}
        version: develop
        update: no
      with_items: "{{ projects }}"
      tags:
        - projects
