---
roles:
  - name: bussmeyer.dotfiles
    src: https://github.com/Bussmeyer/ansible-role-dotfiles
    version: "master"

  - name: elliotweiser.osx-command-line-tools

  - name: viasite-ansible.zsh

collections:
  - name: geerlingguy.mac
