#!/bin/bash

BGreen='\e[1;32m'       # Green
BRed='\e[1;31m'         # Red
Color_Off='\e[0m'       # Text Reset

function setStatusMessage {
    printf "${IRed} --> ${BGreen}$1${Color_Off}\n" 1>&2
}

function exists {
  if command -v $1 >/dev/null 2>&1
  then
    return 0
  else
    return 1
  fi
}

function install_ansible {
    PIP_VERSION=$(pip3 --version | cut -d' ' -f2 | cut -d. -f1)

    if ! exists pip3; then
        setStatusMessage "Install PIP"
        sudo easy_install --quiet pip nose tornado
    else
        pip3 install --upgrade pip
    fi
    if ! exists ansible; then
        setStatusMessage "Install Ansible"
        export CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS="1"
        export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
        export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

        # Ansible in PATH
        # https://stackoverflow.com/questions/63177609/zsh-command-not-found-ansible-after-pip-installing
        export PATH="$HOME/Library/Python/3.11/bin:/opt/homebrew/bin:$HOME/Library/Python/3.9/bin:$PATH"

        # Brew in PATH
        export PATH="/usr/local/bin:$PATH"

        # unable to extract tar file though ansible unarchive module in macOS?
        # export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
        # export MANPATH="/usr/local/opt/gnu-tar/libexec/gnuman:$MANPATH"

        pip3 install ansible
    fi
}

function upgrade_ansible {
    pip3 uninstall ansible-core
}

function install_ansible_roles {
    setStatusMessage "Get all the required roles"
    ansible-galaxy install -f -r requirements.yml
}

function run_ansible_playbook {
    setStatusMessage "Running the ansible playbook for your lovely macbook."
    ansible-playbook main.yml -i inventory -K
}

#upgrade_ansible
install_ansible
install_ansible_roles
run_ansible_playbook
