#!/bin/bash

BGreen='\e[1;32m'       # Green
BRed='\e[1;31m'         # Red
Color_Off='\e[0m'       # Text Reset

function setStatusMessage {
    printf "${IRed} --> ${BGreen}$1${Color_Off}\n" 1>&2
}

function exists {
  if command -v $1 >/dev/null 2>&1
  then
    return 0
  else
    return 1
  fi
}

function install_ansible {
    PIP_VERSION=$(pip --version | cut -d' ' -f2 | cut -d. -f1)

    if ! exists pip; then
        setStatusMessage "Install PIP"
        sudo easy_install --quiet pip nose tornado
    else
        if [ "$PIP_VERSION" -lt 10 ]; then
            sudo pip install nose tornado
            setStatusMessage "Update pip"
            curl https://bootstrap.pypa.io/get-pip.py | sudo python
        fi
    fi
    if ! exists ansible; then
        setStatusMessage "Install Ansible"
        pip install --upgrade setuptools --user python
        sudo pip install -q ansible
    fi
}

function install_ansible_roles {
    setStatusMessage "Get all the required roles"
    ansible-galaxy install -f -r requirements.yml
}

function run_ansible_playbook {
    setStatusMessage "Running the ansible playbook for your lovely macbook."
    ansible-playbook main.yml -i inventory -K
}

install_ansible
install_ansible_roles
run_ansible_playbook
