---
- name: set mac defaults
  osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items: "{{ osx_defaults }}"

- name: Restart SystemUIServer e.g. show date in menu
  command: killall SystemUIServer
