---
- name: Create ~/Projects directory
  file: path=~/Projects state=directory

- name: Create ~/Projects/Sources directory
  file: path=~/Projects/Sources state=directory

- name: Create ~/Projects/Work directory
  file: path=~/Projects/Work state=directory

- name: Create ~/Projects/Playground directory
  file: path=~/Projects/Playground state=directory

- name: Create hint in directories
  file: path=~/Projects/Playground/all-things-that-could-be-deleted state=touch

- name: Set project specific gitconfig includes
  template:
    src: templates/gitconfig_local
    dest: ~/.gitconfig_local
    mode: "0600"

- name: Check if .gitconfig Work exists
  stat:
    path: "~/Projects/Work/.gitconfig"
  register: gitconfig_file_work

- name: Create .gitconfig Work if it doesn't exist
  copy:
    content: ""
    dest: "~/Projects/Work/.gitconfig"
    mode: "0600"
  when: not gitconfig_file_work.stat.exists

- name: Check if .gitconfig Sources exists
  stat:
    path: "~/Projects/Sources/.gitconfig"
  register: gitconfig_file_sources

- name: Create .gitconfig Sources if it doesn't exist
  copy:
    content: ""
    dest: "~/Projects/Sources/.gitconfig"
    mode: "0600"
  when: not gitconfig_file_sources.stat.exists
